server:
  port: 8080
  address: localhost
logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true