name: Development

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      projectName: ${{ steps.project_details.outputs.project_name }}
      projectVersion: ${{ steps.project_details.outputs.project_version }}

    steps:
      - uses: actions/checkout@v4
      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

  api:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build API
        run: |
          mvn -T 1C -pl yue-core-api -B install --file pom.xml
      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: YueAPI-${{ env.projectVersion }}-b${{ github.run_number }}
          path: api/target/${{ env.projectName }}API-${{ env.projectVersion }}.jar

  yue:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Yue
        run: |
          mvn -T 1C -B install --file pom.xml
      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: Yue-${{ env.projectVersion }}-b${{ github.run_number }}
          path: yue-core-bootstrap/target/${{ env.projectName }}-${{ env.projectVersion }}.jar